import "server-only";
import { getProviderByName } from "../provider";
import { BLOCK_PREFIX, renderBlock } from "@/lib/blocks/render-block";
import type { BlockSpec } from "@/lib/blocks/render-block";
import { validateLiquidSnippet } from "@/lib/blocks/liquid-validate";
import type { DesignTokens } from "@/lib/blocks/design-tokens";
import type { BlocksProduct } from "@/lib/blocks/product-json";

/**
 * Liquid Blocks WP-C — generate the snippet with Claude, and never trust it.
 *
 * # The arrangement, and why it isn't quite what the brief describes
 * The brief asks for the Liquid to be generated by Claude, with a prompt that
 * demands scoped CSS — "esa es la garantía técnica de 'no rompe'". The prompt
 * is here and says exactly that. But a prompt is a request, and the cost of it
 * being ignored once is a merchant pasting a global `img { }` rule into a live
 * storefront. So the actual guarantee is `validateLiquidSnippet`, which checks
 * every selector the model wrote, and the deterministic template — the very
 * code that rendered the preview — is the fallback when the check fails.
 *
 * That gives three properties worth having:
 *   - the model can improve phrasing and Liquid idiom, which is what it's good
 *     at, without being load-bearing for safety;
 *   - a snippet that reaches the merchant has been mechanically verified, not
 *     merely asked nicely;
 *   - the floor is the block they already approved in the preview, so the worst
 *     case is "exactly what you saw" rather than "nothing".
 *
 * `source` is returned so this stays honest in the telemetry: if the model is
 * being rejected often, we should know rather than quietly shipping templates.
 */

export type LiquidGenerationSource = "model" | "template";

export interface LiquidGenerationResult {
  liquid: string;
  source: LiquidGenerationSource;
  /** Why the model's output was refused, when it was. For logs, not the user. */
  rejections: string[];
}

interface LiquidToolOutput {
  liquid: string;
}

const TOOL = {
  name: "emit_liquid_block",
  description:
    "Return a single self-contained Shopify Liquid snippet for a product page.",
  schema: {
    type: "object",
    properties: {
      liquid: {
        type: "string",
        description:
          "The complete snippet: one <style> block followed by one root element. No explanation, no markdown fences.",
      },
    },
    required: ["liquid"],
  },
} as const;

function systemPrompt(): string {
  return [
    "You write additive Shopify Liquid snippets that a merchant pastes into a product template.",
    "",
    "ABSOLUTE RULES — a snippet that breaks any of these is discarded:",
    `1. Every CSS selector MUST start with .${BLOCK_PREFIX}. Never style a bare element (body, img, a, button, h1…), never a bare *, never :root, and never a selector that merely CONTAINS the prefix (e.g. "body .${BLOCK_PREFIX}"). Descendants are fine — ".${BLOCK_PREFIX} *" and ".${BLOCK_PREFIX}__media img" both stay inside the block.`,
    `2. Never use a sibling combinator (~ or +) after the block class: ".${BLOCK_PREFIX} ~ *" reaches OUT of the block and would restyle the theme elements beside it.`,
    "3. Never use position:fixed or position:sticky. A block sits in the flow of the page; pinning it to the window can cover the whole store.",
    `4. Declare custom properties on .${BLOCK_PREFIX} itself, never on :root.`,
    "5. No <script>, <iframe>, <link>, <base>, <meta>, <object>, <embed> or <form>. A nested <form> would break the theme's own product form, and the block is pasted inside it.",
    "6. No @import, no url(http…), no on* attributes.",
    "7. No {% render %}, {% include %}, {% section %}, {% javascript %}, {% stylesheet %}, {% schema %} — the snippet must stand alone.",
    "8. Exactly one <style> block and exactly one root element carrying the block class.",
    "",
    "DESIGN RULES:",
    "- Use ONLY the design tokens given. Never introduce a colour, font or radius that isn't among them. The whole point is that the block wears the store's own clothes.",
    "- Read product values from Liquid (`{{ product.title }}`, `{{ product.price | money }}`) rather than baking today's values in. The snippet lives in the theme for a long time.",
    "- Prices go through the `money` filter, always.",
    "",
    "TRUTHFULNESS RULES — these matter more than the styling:",
    "- Render ONLY the claims supplied in the block content. Do not add a badge, guarantee, shipping promise, rating or statistic that was not given to you, however natural it would look.",
    "- Do not soften, embellish or 'improve' a claim into something stronger than what was supplied.",
    "- If a field is empty, omit that element entirely rather than inventing filler.",
    "",
    "Return the snippet through the tool. No prose, no markdown fences.",
  ].join("\n");
}

function userPrompt(input: {
  spec: BlockSpec;
  tokens: DesignTokens;
  product: BlocksProduct;
  reference: string;
  problems?: string[];
}): string {
  const { tokens, product, spec, reference, problems } = input;
  const parts = [
    `BLOCK TYPE: ${spec.type}`,
    "",
    "DESIGN TOKENS measured from this exact store (use these and nothing else):",
    JSON.stringify(
      { palette: tokens.palette, type: tokens.type, shape: tokens.shape },
      null,
      2,
    ),
    "",
    "PRODUCT (for context — read the live values from Liquid, don't paste these):",
    JSON.stringify(
      {
        title: product.title,
        vendor: product.vendor,
        productType: product.productType,
        variantCount: product.variants.length,
      },
      null,
      2,
    ),
    "",
    "BLOCK CONTENT — every claim the merchant supplied. Render these and nothing more:",
    JSON.stringify(spec, null, 2),
    "",
    "REFERENCE IMPLEMENTATION — this is what the merchant already approved in the",
    "preview. Match its structure and class names. You may improve the Liquid idiom",
    "and the markup's semantics; you may not change what it claims or how it looks:",
    reference,
  ];
  if (problems?.length) {
    parts.push(
      "",
      "YOUR PREVIOUS ATTEMPT WAS REJECTED. Fix exactly these and return the whole snippet again:",
      problems.map((p) => `- ${p}`).join("\n"),
    );
  }
  return parts.join("\n");
}

export async function generateLiquidBlock(input: {
  spec: BlockSpec;
  tokens: DesignTokens;
  product: BlocksProduct;
  currency: string | null;
  /** Absolute epoch-ms the call must finish by. See lib/deadline.ts. */
  deadlineAt?: number;
}): Promise<LiquidGenerationResult> {
  // Built first, always. It's both the fallback and the reference the model is
  // asked to match, so the two can't drift into different-looking blocks.
  const template =
    renderBlock({
      spec: input.spec,
      tokens: input.tokens,
      product: input.product,
      currency: input.currency,
      mode: "liquid",
    }).liquid ?? "";

  /**
   * The template is checked too — as a canary, not as a gate.
   *
   * Review pointed out that the fallback path had no validation at all, which
   * meant the code that actually ships today was the only thing in the feature
   * nothing checked. It's checked now. But a failure here is NOT a reason to
   * refuse the export: this is our own tested code, and by far the likeliest
   * cause of it failing is a false positive in the validator rather than a real
   * escape. Refusing would turn a validator bug into a paid export that
   * produces nothing, which is worse than shipping a block the test suite
   * already proves is scoped. So it screams in the logs and continues.
   */
  const templateCheck = validateLiquidSnippet(template);
  if (!templateCheck.ok) {
    console.error(
      `[blocks] OUR OWN template failed validation — this is a bug in render-block.ts or in the validator: ${templateCheck.problems.join(" | ")}`,
    );
  }

  if (!process.env.ANTHROPIC_API_KEY) {
    // Not an error worth failing an export over: the merchant gets exactly the
    // block they approved, which is the whole promise anyway.
    return { liquid: template, source: "template", rejections: ["no ANTHROPIC_API_KEY"] };
  }

  const rejections: string[] = [];
  let problems: string[] | undefined;

  // Two attempts, not more. A model that produced an unscoped selector twice
  // with the problems handed back is not going to be talked round on a third
  // try, and an export is a request someone is waiting on.
  for (let attempt = 0; attempt < 2; attempt++) {
    try {
      const provider = await getProviderByName("anthropic");
      const out = await provider.generateStructured<LiquidToolOutput>(TOOL, {
        system: systemPrompt(),
        parts: [
          {
            text: userPrompt({
              spec: input.spec,
              tokens: input.tokens,
              product: input.product,
              reference: template,
              problems,
            }),
          },
        ],
        temperature: 0.2,
        maxTokens: 4096,
        deadlineAt: input.deadlineAt,
      });

      // Models like to wrap code in fences however firmly you ask them not to.
      const liquid = (out.liquid ?? "")
        .replace(/^\s*```(?:liquid|html)?\s*/i, "")
        .replace(/\s*```\s*$/i, "")
        .trim();

      const check = validateLiquidSnippet(liquid);
      if (check.ok) return { liquid, source: "model", rejections };

      problems = check.problems;
      rejections.push(...check.problems);
    } catch (err) {
      rejections.push((err as Error).message);
      break;
    }
  }

  console.warn(
    `[blocks] model snippet rejected, falling back to template: ${rejections.join(" | ")}`,
  );
  return { liquid: template, source: "template", rejections };
}
